name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-and-test:
    name: Install and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff validation
        run: uv run ruff check .

      - name: Run Ruff format check
        run: uv run ruff format --check .

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-pages:
    name: Deploy documentation to GitHub Pages
    needs: lint-and-test

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compilar LaTeX (docs/main.tex)
        uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098
        with:
          root_file: main.tex
          working_directory: docs/pdf
          latexmk_use_xelatex: true

      - name: Build Docusaurus
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/reinanhs/template-documentacao-ia-juridica.git
          cd template-documentacao-ia-juridica
          rm -rf docs
          cp -r ../docs docs
          npm ci --ignore-scripts
          npm run build
          cp ../docs/pdf/main.pdf build/contribuicao-individual.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './template-documentacao-ia-juridica/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
